# Generated by Django 3.2.12 on 2022-04-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('valeur', models.FloatField()),
                ('enregistreur', models.CharField(max_length=40)),
                ('horaire', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
