# Generated by Django 3.2.13 on 2022-04-15 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_indicateur_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='horaire',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
