# Generated by Django 3.2.13 on 2022-04-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_indicateur_horaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicateur',
            name='horaire',
        ),
    ]
