# Generated by Django 3.2.13 on 2022-04-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_indicateur_horaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('valeur', models.FloatField()),
                ('enregistreur', models.CharField(max_length=40)),
                ('horaire', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
