# Generated by Django 3.2.13 on 2022-04-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_indicateurimport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicateurimport',
            old_name='id',
            new_name='id_indice',
        ),
    ]
