# Generated by Django 3.2.13 on 2022-05-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_essaie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=400)),
                ('grade', models.CharField(max_length=400)),
                ('service', models.CharField(max_length=400)),
                ('émail', models.EmailField(max_length=254)),
            ],
        ),
    ]
