# Generated by Django 3.2.13 on 2022-05-07 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20220507_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='value',
        ),
        migrations.RemoveField(
            model_name='essaie',
            name='équipe',
        ),
        migrations.AddField(
            model_name='essaie',
            name='équipe',
            field=models.CharField(default=datetime.datetime(2022, 5, 7, 11, 21, 45, 215573, tzinfo=utc), max_length=400),
            preserve_default=False,
        ),
    ]
