# Generated by Django 3.2.13 on 2022-05-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220507_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='label',
            new_name='fullName',
        ),
    ]
