# Generated by Django 3.2.13 on 2022-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_label_utilisateur_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essaie',
            name='équipe',
        ),
        migrations.AddField(
            model_name='essaie',
            name='équipe',
            field=models.ManyToManyField(to='myapp.Utilisateur'),
        ),
    ]
