# Generated by Django 3.2.13 on 2022-05-08 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20220507_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default=datetime.datetime(2022, 5, 8, 12, 52, 35, 226873, tzinfo=utc), max_length=400),
            preserve_default=False,
        ),
    ]
