# Generated by Django 3.2.13 on 2022-05-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_utilisateur_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='fullName',
            new_name='username',
        ),
    ]
