# Generated by Django 3.2.13 on 2022-05-27 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_utilisateur_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='valeur_color',
            field=models.CharField(default=datetime.datetime(2022, 5, 27, 22, 28, 59, 42899, tzinfo=utc), max_length=6),
            preserve_default=False,
        ),
    ]
