# Generated by Django 3.2.13 on 2022-05-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_indicateur_valeur_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicateur',
            name='valeur_color',
        ),
    ]
